---
blank_issues_enabled: false
contact_links:
  - name: NetasCode Site
    url: https://netascode.cisco.com
    about: Please review additional information on the NetasCode site.
  - name: Webex Room
    url: https://eurl.io/#qLKerBXmR
    about: Join the "SDWAN General - Network as Code" Webex room for discussions.
